### ISSUE TITLE
Portrait images are stretched horizontally

### ISSUE THREAD

**Issue by bwees** [Jake-Short/swiftui-image-viewer#9]
I noticed that when you give the Image viewer a portrait image, it shows a stretched version as show below:

![IMG_0609](https://user-images.githubusercontent.com/12686250/88109885-41953400-cb79-11ea-9d47-5aa08a817d3d.JPG)
![IMG_2702](https://user-images.githubusercontent.com/12686250/88109892-4528bb00-cb79-11ea-8617-f9df24c5754e.jpg)

**Comment by Jake-Short** [comment]
Thanks for your report!

I am attempting to re-create this issue, but it appears to be working on both small and large screens (iPhone SE and iPhone 11 Pro, see below):
![Simulator Screen Shot - iPhone 11 Pro - 2020-07-21 at 14 51 06](https://user-images.githubusercontent.com/46853220/88111128-3551ac80-cb62-11ea-8ac8-9ec03067faed.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-21 at 14 50 57](https://user-images.githubusercontent.com/46853220/88111132-3a166080-cb62-11ea-8bdd-0da8b69817f7.png)

Could you provide more details to recreate this bug, such as:
- Simulator/device
- Xcode version
- iOS target version

**Comment by bwees** [comment]
I am on Xcode 11.6 as well as ios 13.6. My target is 13.5.

The only weird thing is that I am showing this in a sheet, not a regular
view.

**Comment by Jake-Short** [comment]
It appears that this issue is due to a bug with SwiftUI. The issue appears in iOS 13.6, but is fixed in iOS 14 (see below).

iPhone SE 2, iOS 14
<img src="https://user-images.githubusercontent.com/46853220/88212988-f7f62900-cc0c-11ea-83fb-055f03962b46.png" width="250" />

iPhone SE 2, iOS 13.6
<img src="https://user-images.githubusercontent.com/46853220/88212997-fcbadd00-cc0c-11ea-999b-5474394807af.png" width="250" />

I am currently working on adding a fix that will allow it to work across all versions.

**Comment by Jake-Short** [comment]
By explicitly specifying an aspect ratio, the issue should be fixed (see PR #12).

**Comment by bwees** [comment]
What specific way should I set the aspect ratio?

**Comment by bwees** [comment]
Never mind! I just looked at the pull request code
